### ISSUE TITLE
Color picker input never opens in newer versions of codemirror (6.0.1)

### ISSUE THREAD

**Issue by Hit-And-Run-5677** [replit/Codemirror-CSS-color-picker#18] opened 2024-02-08 16:34 UTC
In codemirror 6 @replit/codemirror-css-color-picker seems to be not working. It is creating the widget with the color picker input aside the color values but clicking it does nothing. The widget's color picker input never opens. I have done some digging into this and i think this is due to the core click event handling of codemirror. In chrome devtools, the widget has a click event assigned to .cm-content.cm-lineWrapping comming from @codemirror/view & when i remove that event everything seems to perfectly work. I have tried hours removing that in code by anyhow editing the node_modules but i cannot succeed. Please fix it.

**Comment by Alick09** [comment] 2024-04-05 15:26
For me it works perfectly. Seems that problem in your setup.

**Comment by sergeichestakov** [comment] 2024-04-06 23:37
I haven't been able to reproduce this and the library has changed quite a bit since this issue was opened. I would try the suggestion in https://github.com/replit/Codemirror-CSS-color-picker/pull/21#issue-2229198059 and see if you get any luck. Will close this out in the meantime but please let me know if you're still running into this!

**Closed by sergeichestakov** 2024-04-06 23:37 UTC
